[build]
  publish = "__sapper__/export/"
  command = "npm run e2e:headless && npm run export"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"